import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create sample instructors
  const instructors = [
    {
      email: 'maria.salsa@example.com',
      name: 'Maria Rodriguez',
      profile: {
        slug: 'maria-rodriguez',
        displayName: 'Maria Rodriguez',
        bio: 'Professional salsa instructor with 15 years of experience. Specializing in Cuban and LA style salsa.',
        styles: JSON.stringify(['Salsa', 'Bachata']),
        skillLevels: JSON.stringify(['Beginner', 'Intermediate', 'Advanced']),
        offersPrivate: true,
        privateRateHourly: 80,
        offersGroup: true,
        groupRatePerClass: 20,
        groupClassNotes: 'Tuesdays and Thursdays at Dance Charlotte',
        locationType: 'DANCE_SCHOOL',
        neighborhood: 'Uptown',
        travelRadiusMiles: 15,
        paymentCash: true,
        paymentVenmo: 'maria-salsa',
        instagramUrl: 'https://instagram.com/mariasalsa',
      },
    },
    {
      email: 'carlos.bachata@example.com',
      name: 'Carlos Mendez',
      profile: {
        slug: 'carlos-mendez',
        displayName: 'Carlos Mendez',
        bio: 'Bachata specialist trained in the Dominican Republic. Passionate about sensual and traditional bachata styles.',
        styles: JSON.stringify(['Bachata', 'Salsa']),
        skillLevels: JSON.stringify(['Beginner', 'Intermediate']),
        offersPrivate: true,
        privateRateHourly: 75,
        offersGroup: false,
        locationType: 'FLEXIBLE',
        neighborhood: 'South End',
        travelRadiusMiles: 10,
        paymentCash: true,
        paymentVenmo: 'carlos-bachata',
        paymentCashApp: 'carlosbachata',
      },
    },
    {
      email: 'sophie.kizomba@example.com',
      name: 'Sophie Laurent',
      profile: {
        slug: 'sophie-laurent',
        displayName: 'Sophie Laurent',
        bio: 'Kizomba and urban kiz instructor. Bringing the Angolan dance culture to Charlotte.',
        styles: JSON.stringify(['Kizomba', 'Zouk']),
        skillLevels: JSON.stringify(['Beginner', 'Intermediate', 'Advanced']),
        offersPrivate: true,
        privateRateHourly: 90,
        offersGroup: true,
        groupRatePerClass: 25,
        groupClassNotes: 'Sundays at Studio 1521',
        locationType: 'STUDIO',
        neighborhood: 'NoDa',
        address: '123 N Davidson St, Charlotte, NC',
        paymentCash: true,
        paymentVenmo: 'sophie-kiz',
        paymentPayPal: 'sophie.laurent',
        instagramUrl: 'https://instagram.com/sophiekizomba',
      },
    },
    {
      email: 'diego.tango@example.com',
      name: 'Diego Fernandez',
      profile: {
        slug: 'diego-fernandez',
        displayName: 'Diego Fernandez',
        bio: 'Argentine tango instructor with authentic Buenos Aires training. Private lessons and milonga hosting.',
        styles: JSON.stringify(['Tango']),
        skillLevels: JSON.stringify(['Beginner', 'Intermediate', 'Advanced']),
        offersPrivate: true,
        privateRateHourly: 100,
        offersGroup: true,
        groupRatePerClass: 30,
        locationType: 'STUDIO',
        neighborhood: 'Plaza Midwood',
        paymentCash: true,
        paymentVenmo: 'diego-tango',
        websiteUrl: 'https://charlottetango.com',
      },
    },
    {
      email: 'luna.zouk@example.com',
      name: 'Luna Silva',
      profile: {
        slug: 'luna-silva',
        displayName: 'Luna Silva',
        bio: 'Brazilian zouk and lambada expert. Creating magical connections on the dance floor.',
        styles: JSON.stringify(['Zouk', 'Salsa']),
        skillLevels: JSON.stringify(['Beginner', 'Intermediate']),
        offersPrivate: true,
        privateRateHourly: 85,
        offersGroup: false,
        locationType: 'TRAVEL_TO_STUDENT',
        neighborhood: 'Dilworth',
        travelRadiusMiles: 20,
        paymentCash: true,
        paymentVenmo: 'luna-zouk',
        instagramUrl: 'https://instagram.com/lunazouk',
      },
    },
    {
      email: 'alex.multi@example.com',
      name: 'Alex Thompson',
      profile: {
        slug: 'alex-thompson',
        displayName: 'Alex Thompson',
        bio: 'Multi-style instructor specializing in beginner-friendly lessons. Let\'s get you dancing!',
        styles: JSON.stringify(['Salsa', 'Bachata', 'Kizomba']),
        skillLevels: JSON.stringify(['Beginner']),
        offersPrivate: true,
        privateRateHourly: 60,
        offersGroup: true,
        groupRatePerClass: 15,
        groupClassNotes: 'Wednesdays and Fridays at Community Center',
        locationType: 'FLEXIBLE',
        neighborhood: 'Myers Park',
        paymentCash: true,
        paymentCashApp: 'alexdance',
      },
    },
    {
      email: 'rosa.salsa@example.com',
      name: 'Rosa Martinez',
      profile: {
        slug: 'rosa-martinez',
        displayName: 'Rosa Martinez',
        bio: 'Salsa on2 specialist. Former professional dancer, now sharing my passion through teaching.',
        styles: JSON.stringify(['Salsa']),
        skillLevels: JSON.stringify(['Intermediate', 'Advanced']),
        offersPrivate: true,
        privateRateHourly: 95,
        offersGroup: true,
        groupRatePerClass: 25,
        locationType: 'DANCE_SCHOOL',
        neighborhood: 'Uptown',
        paymentVenmo: 'rosa-salsa',
        paymentPayPal: 'rosa.martinez',
      },
    },
    {
      email: 'marco.bachata@example.com',
      name: 'Marco Diaz',
      profile: {
        slug: 'marco-diaz',
        displayName: 'Marco Diaz',
        bio: 'Competition-level bachata instructor. Perfect your technique and musicality.',
        styles: JSON.stringify(['Bachata']),
        skillLevels: JSON.stringify(['Intermediate', 'Advanced']),
        offersPrivate: true,
        privateRateHourly: 110,
        offersGroup: false,
        locationType: 'STUDIO',
        neighborhood: 'Cotswold',
        address: '456 Sharon Amity Rd, Charlotte, NC',
        paymentCash: true,
        paymentVenmo: 'marco-bachata',
        instagramUrl: 'https://instagram.com/marcodance',
        websiteUrl: 'https://marcodiaz.dance',
      },
    },
  ]

  for (const instructor of instructors) {
    const user = await prisma.user.upsert({
      where: { email: instructor.email },
      update: {},
      create: {
        email: instructor.email,
        name: instructor.name,
        role: 'INSTRUCTOR',
      },
    })

    await prisma.instructorProfile.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        ...instructor.profile,
      },
    })

    console.log(`✅ Created instructor: ${instructor.name}`)
  }

  // Create sample events
  const events = [
    {
      status: 'APPROVED',
      title: 'Friday Night Salsa Social',
      eventType: 'SOCIAL',
      styles: JSON.stringify(['Salsa', 'Bachata']),
      startDateTime: new Date('2026-02-14T20:00:00'),
      endDateTime: new Date('2026-02-15T01:00:00'),
      venueName: 'The Salsa Room',
      neighborhood: 'Uptown',
      address: '100 N Tryon St, Charlotte, NC',
      price: 15,
      organizerName: 'Charlotte Salsa Collective',
      organizerEmail: 'info@cltsalsa.com',
      instagramUrl: 'https://instagram.com/cltsalsa',
      description: 'Join us for the hottest salsa night in Charlotte! DJs spinning the best Latin music, beginner lesson at 8pm, social dancing until 1am.',
    },
    {
      status: 'APPROVED',
      title: 'Bachata Workshop with International Instructors',
      eventType: 'WORKSHOP',
      styles: JSON.stringify(['Bachata']),
      startDateTime: new Date('2026-02-16T14:00:00'),
      endDateTime: new Date('2026-02-16T18:00:00'),
      venueName: 'Dance Charlotte Studio',
      neighborhood: 'South End',
      price: 50,
      organizerName: 'Bachata Charlotte',
      organizerEmail: 'events@bachataclt.com',
      websiteUrl: 'https://bachataclt.com/workshop',
      description: 'Special 4-hour workshop covering sensual bachata styling, partner work, and musicality. All levels welcome!',
    },
    {
      status: 'APPROVED',
      title: 'Kizomba Fusion Night',
      eventType: 'SOCIAL',
      styles: JSON.stringify(['Kizomba', 'Zouk']),
      startDateTime: new Date('2026-02-17T21:00:00'),
      venueName: 'Studio 1521',
      neighborhood: 'NoDa',
      price: null,
      organizerName: 'Charlotte Kizomba Scene',
      organizerEmail: 'hello@cltkizomba.com',
      instagramUrl: 'https://instagram.com/cltkizomba',
      description: 'FREE kizomba and urban kiz social. Beginner lesson at 9pm. BYOB venue.',
    },
    {
      status: 'APPROVED',
      title: 'Tango Milonga',
      eventType: 'TANGO_MILONGA',
      styles: JSON.stringify(['Tango']),
      startDateTime: new Date('2026-02-18T19:30:00'),
      endDateTime: new Date('2026-02-18T23:00:00'),
      venueName: 'Plaza Midwood Community Center',
      neighborhood: 'Plaza Midwood',
      price: 10,
      organizerName: 'Charlotte Tango Society',
      organizerEmail: 'milonga@clttango.org',
      description: 'Traditional Argentine tango milonga. Live music from 8-9pm. Light refreshments provided.',
    },
    {
      status: 'APPROVED',
      title: 'Beginner Salsa Class Series (4 weeks)',
      eventType: 'GROUP_CLASS',
      styles: JSON.stringify(['Salsa']),
      startDateTime: new Date('2026-02-19T19:00:00'),
      endDateTime: new Date('2026-02-19T20:00:00'),
      venueName: 'Community Dance Studio',
      neighborhood: 'Dilworth',
      price: 60,
      organizerName: 'Maria Rodriguez',
      organizerEmail: 'maria.salsa@example.com',
      description: 'Learn salsa basics in this 4-week series. No partner needed! $60 for all 4 classes.',
    },
    {
      status: 'APPROVED',
      title: 'Zouk Sundays',
      eventType: 'GROUP_CLASS',
      styles: JSON.stringify(['Zouk']),
      startDateTime: new Date('2026-02-23T15:00:00'),
      endDateTime: new Date('2026-02-23T17:00:00'),
      venueName: 'The Dance Loft',
      neighborhood: 'South End',
      price: 20,
      organizerName: 'Luna Silva',
      organizerEmail: 'luna.zouk@example.com',
      instagramUrl: 'https://instagram.com/lunazouk',
      description: 'Weekly zouk class and practice session. All levels. Stay for social dancing after!',
    },
    {
      status: 'APPROVED',
      title: 'Charlotte Latin Dance Festival',
      eventType: 'FESTIVAL',
      styles: JSON.stringify(['Salsa', 'Bachata', 'Kizomba', 'Zouk']),
      startDateTime: new Date('2026-03-01T10:00:00'),
      endDateTime: new Date('2026-03-03T23:00:00'),
      venueName: 'Hilton Charlotte Center City',
      neighborhood: 'Uptown',
      address: '222 E 3rd St, Charlotte, NC',
      price: 150,
      organizerName: 'CLT Dance Events',
      organizerEmail: 'festival@cltdance.com',
      websiteUrl: 'https://cltdancefestival.com',
      instagramUrl: 'https://instagram.com/cltdancefest',
      description: '3-day festival featuring workshops with international instructors, performances, and nightly socials. Early bird pricing available!',
    },
    {
      status: 'APPROVED',
      title: 'Bachata Ladies Styling Workshop',
      eventType: 'WORKSHOP',
      styles: JSON.stringify(['Bachata']),
      startDateTime: new Date('2026-02-20T18:00:00'),
      endDateTime: new Date('2026-02-20T20:00:00'),
      venueName: 'Dance Charlotte Studio',
      neighborhood: 'South End',
      price: 30,
      organizerName: 'Maria Rodriguez',
      organizerEmail: 'maria.salsa@example.com',
      description: 'Ladies only workshop focusing on bachata styling, body movement, and confidence. All levels welcome.',
    },
    {
      status: 'APPROVED',
      title: 'Salsa & Bachata Mixer',
      eventType: 'SOCIAL',
      styles: JSON.stringify(['Salsa', 'Bachata']),
      startDateTime: new Date('2026-02-21T20:00:00'),
      venueName: 'Rooftop 210',
      neighborhood: 'Uptown',
      price: 20,
      organizerName: 'Charlotte Social Dance',
      organizerEmail: 'socials@cltdance.com',
      instagramUrl: 'https://instagram.com/cltsocialdance',
      description: 'Outdoor rooftop social with stunning city views. Salsa and bachata all night. Food and drinks available for purchase.',
    },
    {
      status: 'APPROVED',
      title: 'Valentine\'s Kizomba Special',
      eventType: 'SOCIAL',
      styles: JSON.stringify(['Kizomba']),
      startDateTime: new Date('2026-02-14T19:00:00'),
      endDateTime: new Date('2026-02-14T23:00:00'),
      venueName: 'Studio 1521',
      neighborhood: 'NoDa',
      price: 25,
      organizerName: 'Sophie Laurent',
      organizerEmail: 'sophie.kizomba@example.com',
      description: 'Romantic Valentine\'s kizomba evening. Live DJ, complimentary champagne, and chocolate. Dress code: elegant.',
    },
  ]

  for (const event of events) {
    await prisma.event.create({
      data: event,
    })
    console.log(`✅ Created event: ${event.title}`)
  }

  console.log('🎉 Seeding completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
